import { shoutoutCommand } from './shoutout.js';

// {u} is replaced with the target's mention. Keep these playful — no looks, family, or identity.
const disses = [
  '{u}, your ping is higher than your rank. 📶',
  '{u} plays like the tutorial is still on. 🎮',
  '{u}, even the bots in practice mode feel sorry for you. 🤖',
  '{u} brings a spoon to a sword fight. 🥄⚔️',
  '{u}, your K/D ratio is a cry for help. 📉',
  '{u} is the reason the respawn button exists. 🔁',
  '{u}, you\'re not AFK — you just play like it. 💤',
  '{u} has main character energy with side quest results. 🗺️',
  '{u}, your strategy is "hope." It\'s not working. 🙏',
  '{u} would lose a 1v1 against a loading screen. ⏳',
  '{u}, you\'re like a cloud. When you disappear, the day gets better. ☁️',
  '{u} is proof that "carry" is a verb other people do. 🎒',
  '{u}, I\'d roast you harder, but my mom said not to burn trash. 🔥🗑️',
  '{u} sets alarms for Mine Wars and still shows up late. ⏰',
  '{u}, you have the reflexes of a sleeping tanod. 😴',
  '{u} types "gg" before the match even starts. Respect the confidence, not the skill. 🫡',
  '{u}, your Wi-Fi isn\'t the problem. You are. 📡',
  '{u} is the human version of a participation trophy. 🏅',
  '{u}, you\'re not useless — you can always serve as a bad example. 📚',
  '{u} studies the meta and still picks wrong. 📖',
  '{u}, you\'re the reason the enemy team has a highlight reel. 🎬',
  '{u} thinks "strategy" is a type of snack. 🍿',
  '{u}, your aim is so bad even the walls feel safe. 🧱',
  '{u} got lost in the lobby. The lobby. 🧭',
  '{u}, you\'re not a noob — noobs at least improve. 🐣',
  '{u} rage quits in single player. 😤',
  '{u}, your gameplay could be used as a sleep aid. 🛌',
  '{u} reads patch notes and still gets surprised. 📝',
  '{u}, even autocorrect gave up on you. ⌨️',
  '{u} brings snacks to the match and contributes nothing else. 🍪',
  '{u}, you\'re like a software update: nobody asked for you and you take forever. 🔄',
  '{u} is on a winning streak — of losses. 🏳️',
  '{u}, your battle cry is just "wait for me." 🏃',
  '{u} calls it "tactical feeding." We call it feeding. 🍽️',
  '{u}, your teammates pray before every match you join. 🙏',
  '{u} has 99 problems and positioning is all of them. 📍',
  '{u}, you\'re the plot twist nobody wanted. 🌀',
  '{u} would get outplayed by a door. 🚪',
  '{u}, the minimap has more awareness than you. 🗺️',
  '{u} thinks cooldowns are a suggestion. ⏲️',
  '{u}, you have the timing of a jeepney with no schedule. 🚙',
  '{u} shows up to Ancient Battlefield just to sightsee. 📸',
  '{u}, you\'re so slow, the loading screen waits for YOU. 🐌',
  '{u} is the reason we can\'t have nice things. 🧸',
  '{u}, your game sense is on airplane mode. ✈️',
  '{u} practices every day and somehow gets worse. 📉',
  '{u}, you\'re the Wi-Fi signal in the bathroom: weak and unreliable. 🚽📶',
  '{u} counters themselves. Impressive, honestly. 🔃',
  '{u}, you\'re a limited edition — limited skill. 🏷️',
  '{u} thinks "support" means emotional support only. 🫂',
  '{u}, you peaked in the character select screen. 🧍',
  '{u} gets carried so often they should pay a delivery fee. 📦',
  '{u}, even your excuses have lag. 🐢',
  '{u} got a participation award and still lost it. 🏆',
  '{u}, you\'re like a phone at 1%: dramatic and about to die. 🔋',
  '{u} brings a map to a respawn point. 🧭',
  '{u}, the tutorial called — it wants a rematch. 📞',
  '{u} is a legend. A cautionary one. 📜',
  '{u}, you move like you\'re buffering in real life. ⏯️',
  '{u} thinks the enemy nexus is a vacation spot. 🏖️',
];

const botComebacks = [
  'Nice try. I run 24/7 on a free server and I still have better uptime than you. 😎',
  'You tried to diss the bot. The bot is not impressed. 🤖',
];

export const diss = shoutoutCommand({
  name: 'diss',
  description: 'Playfully roast someone',
  userDescription: 'Who to roast',
  lines: disses,
  botLines: botComebacks,
});
