// Lines for /judge. {u} is replaced with the target's mention.
// Keep roasts playful — no looks, family, or identity.

export const disses = [
  '{u}, your ping is higher than your rank. 📶',
  '{u} plays like the tutorial is still on. 🎮',
  '{u}, even the bots in practice mode feel sorry for you. 🤖',
  '{u} brings a spoon to a sword fight. 🥄⚔️',
  '{u}, your K/D ratio is a cry for help. 📉',
  '{u} is the reason the respawn button exists. 🔁',
  '{u}, you\'re not AFK — you just play like it. 💤',
  '{u} has main character energy with side quest results. 🗺️',
  '{u}, your strategy is "hope." It\'s not working. 🙏',
  '{u} would lose a 1v1 against a loading screen. ⏳',
  '{u}, you\'re like a cloud. When you disappear, the day gets better. ☁️',
  '{u} is proof that "carry" is a verb other people do. 🎒',
  '{u}, I\'d roast you harder, but my mom said not to burn trash. 🔥🗑️',
  '{u} sets alarms for Mine Wars and still shows up late. ⏰',
  '{u}, you have the reflexes of a sleeping tanod. 😴',
  '{u} types "gg" before the match even starts. Respect the confidence, not the skill. 🫡',
  '{u}, your Wi-Fi isn\'t the problem. You are. 📡',
  '{u} is the human version of a participation trophy. 🏅',
  '{u}, you\'re not useless — you can always serve as a bad example. 📚',
  '{u} studies the meta and still picks wrong. 📖',
  '{u}, you\'re the reason the enemy team has a highlight reel. 🎬',
  '{u} thinks "strategy" is a type of snack. 🍿',
  '{u}, your aim is so bad even the walls feel safe. 🧱',
  '{u} got lost in the lobby. The lobby. 🧭',
  '{u}, you\'re not a noob — noobs at least improve. 🐣',
  '{u} rage quits in single player. 😤',
  '{u}, your gameplay could be used as a sleep aid. 🛌',
  '{u} reads patch notes and still gets surprised. 📝',
  '{u}, even autocorrect gave up on you. ⌨️',
  '{u} brings snacks to the match and contributes nothing else. 🍪',
  '{u}, you\'re like a software update: nobody asked for you and you take forever. 🔄',
  '{u} is on a winning streak — of losses. 🏳️',
  '{u}, your battle cry is just "wait for me." 🏃',
  '{u} calls it "tactical feeding." We call it feeding. 🍽️',
  '{u}, your teammates pray before every match you join. 🙏',
  '{u} has 99 problems and positioning is all of them. 📍',
  '{u}, you\'re the plot twist nobody wanted. 🌀',
  '{u} would get outplayed by a door. 🚪',
  '{u}, the minimap has more awareness than you. 🗺️',
  '{u} thinks cooldowns are a suggestion. ⏲️',
  '{u}, you have the timing of a jeepney with no schedule. 🚙',
  '{u} shows up to Ancient Battlefield just to sightsee. 📸',
  '{u}, you\'re so slow, the loading screen waits for YOU. 🐌',
  '{u} is the reason we can\'t have nice things. 🧸',
  '{u}, your game sense is on airplane mode. ✈️',
  '{u} practices every day and somehow gets worse. 📉',
  '{u}, you\'re the Wi-Fi signal in the bathroom: weak and unreliable. 🚽📶',
  '{u} counters themselves. Impressive, honestly. 🔃',
  '{u}, you\'re a limited edition — limited skill. 🏷️',
  '{u} thinks "support" means emotional support only. 🫂',
  '{u}, you peaked in the character select screen. 🧍',
  '{u} gets carried so often they should pay a delivery fee. 📦',
  '{u}, even your excuses have lag. 🐢',
  '{u} got a participation award and still lost it. 🏆',
  '{u}, you\'re like a phone at 1%: dramatic and about to die. 🔋',
  '{u} brings a map to a respawn point. 🧭',
  '{u}, the tutorial called — it wants a rematch. 📞',
  '{u} is a legend. A cautionary one. 📜',
  '{u}, you move like you\'re buffering in real life. ⏯️',
  '{u} thinks the enemy nexus is a vacation spot. 🏖️',
  '{u}, your gameplay has more bugs than the game itself. 🐛',
  '{u} is so late to Mine Wars the mines already retired. ⛏️',
  '{u}, you\'re the loading screen tip nobody reads. 💡',
  '{u} joins voice chat just to breathe loudly. 🎙️',
  '{u}, your comeback arc is still buffering. ⏳',
  '{u} thinks "flank" is a type of steak. 🥩',
  '{u}, you\'re the reason the team chat is muted. 🔇',
  '{u} dodges responsibilities better than skill shots. 🏃',
  '{u}, your highlight reel is a 2-second clip of you walking. 🚶',
  '{u} says "one more game" and loses five. 🎮',
  '{u}, you have the stealth of a jeepney horn. 📢',
  '{u} is so AFK their character filed a missing person report. 🕵️',
  '{u}, even the NPCs give you side-eye. 👀',
  '{u} treats every match like a free trial. 🆓',
  '{u}, your ranked journey is a documentary about falling. 📉',
  '{u} still hasn\'t found the settings menu. ⚙️',
  '{u}, you\'re the teammate the matchmaking system warns us about. ⚠️',
  '{u} has the reaction time of a snail on vacation. 🐌🏖️',
  '{u}, your battle plan is just vibes. ✨',
  '{u} got outsmarted by a treasure chest. 📦',
  '{u}, you\'re one bad decision away from a legendary fail compilation. 🎞️',
  '{u} thinks the enemy base is a shopping mall. 🛍️',
  '{u}, your skills are like load on the 15th: gone too fast. 📱',
  '{u} runs into battle like they forgot something at home. 🏠',
  '{u}, your map awareness ends at your own screen. 🖥️',
  '{u} is the plot armor the enemy team needed. 🛡️',
  '{u}, you\'d get lost on a straight road. 🛣️',
  '{u} practices in the mirror and still misses. 🪞',
  '{u}, your cooldowns have cooldowns. ⏲️',
  '{u} is the reason the "report" button got bigger. 🚩',
  '{u}, even your ping feels embarrassed. 📶',
  '{u} carries the team — straight into the enemy spawn. 🎒',
  '{u}, you\'ve got the game sense of a rice cooker. 🍚',
  '{u} types faster than they play. Which is still slow. ⌨️',
  '{u}, your aim is like tricycle fare: never exact. 🛺',
  '{u} gives 110% — to the wrong objective. 🎯',
  '{u}, you\'re the jump scare of our team comp. 😱',
  '{u} saw the tutorial and chose violence against themselves. 🥊',
  '{u}, even autopilot would do better. ✈️',
  '{u} is proof that confidence isn\'t a skill. 💪',
  '{u}, the only thing you\'re consistent at is disconnecting. 🔌',
  '{u} plays like the controller is unplugged. 🎮',
  '{u}, your strategy is a group project where you did nothing. 📚',
  '{u} arrives at Ancient Battlefield after the battlefield is ancient. 🏛️',
  '{u}, your K/D is a phone number with no area code. ☎️',
  '{u} is the respawn timer\'s best customer. 🔁',
  '{u}, your gameplay is sponsored by lag. 🐢',
  '{u} tried to clutch and dropped the whole bag. 👜',
  '{u}, the enemy team sends you thank-you cards. 💌',
  '{u} brings a knife to an airstrike. 🔪',
  '{u}, you\'re a speedrunner — of losing. 🏁',
  '{u} studies strategy videos at 2x speed and remembers none of it. 📺',
  '{u}, even the practice dummy has more kills. 🎯',
  '{u} would lose a staring contest with a wall. 🧱',
  '{u}, your hands are fast but your brain is on ECQ. 🧠',
  '{u} thinks "retreat" is a spa day. 🧖',
  '{u}, you\'re the unskippable ad of this squad. 📺',
  '{u} walks into traps like they\'re sponsored. 🪤',
  '{u}, your teamwork makes the dream... not work. 💤',
  '{u} is a whole tutorial level on what not to do. 📖',
  '{u}, you have main menu energy. 🏠',
  '{u} celebrates too early every single time. 🎉',
  '{u}, your gaming chair isn\'t helping. 🪑',
  '{u} has more excuses than kills. 📝',
  '{u}, you\'re the reason the enemy team smiles. 😁',
  '{u} uses their ultimate on a minion. Every. Time. 💥',
  '{u}, even the respawn music is tired of you. 🎵',
  '{u} thinks "GG EZ" is a greeting. 👋',
  '{u}, your survival instinct is on silent mode. 🔕',
  '{u} is so slow, the game updates before they move. 🔄',
  '{u}, you peaked when you pressed "Play." ▶️',
  '{u} got a tutorial achievement and called it a career. 🏅',
  '{u}, your aim is like Manila traffic: going nowhere. 🚗',
  '{u} is the definition of "trust me, I got this" — they didn\'t. 🙃',
  '{u}, the enemy team calls you "free XP." 🆙',
  '{u} brings the vibes and nothing else. 🎶',
  '{u}, your gameplay could make a coach retire. 🧢',
  '{u} takes the scenic route to every fight. 🌄',
  '{u}, your plan B is also plan A, and both fail. 🅱️',
  '{u} thinks healing is for other people. 🩹',
  '{u}, you\'re a legend in your own loading screen. 🌀',
  '{u} gets killed by fall damage in a flat map. 🪂',
  '{u}, your inventory is 90% useless items. 🎒',
  '{u} would miss a target the size of SM Mall of Asia. 🏬',
  '{u}, even Wi-Fi from the sari-sari store is more reliable. 🏪',
  '{u} plays with their eyes closed. At least it looks like it. 🙈',
  '{u}, your "calculated risk" was not calculated. 🧮',
  '{u} is the reason the spectators leave early. 🚪',
  '{u}, you\'d get outplayed by a sleeping cat. 🐈',
  '{u} thinks the minimap is decoration. 🖼️',
  '{u}, your hero is crying in the character select screen. 😢',
  '{u} forgets their skills exist mid-fight. 🤔',
  '{u}, you\'re the "before" in every before-and-after. 📸',
  '{u} is sponsored by the enemy team. 💸',
  '{u}, even your lucky shots miss. 🍀',
  '{u} is out here making the enemy look like pros. 🏆',
  '{u}, your gameplay is a slideshow presentation. 📊',
  '{u} goes in solo like it\'s a solo concert. Nobody came. 🎤',
  '{u}, your comeback is still in pre-order. 🛒',
  '{u} loots slower than a turtle doing paperwork. 🐢📄',
  '{u}, the game should give you a participation badge. 🎖️',
  '{u} spends 10 minutes on a build and loses in 10 seconds. ⏱️',
  '{u}, your battle cry is a "brb." 🚽',
  '{u} thinks positioning is about where they sit. 🛋️',
  '{u}, the enemy team queues just to meet you. 🤝',
  '{u} would get lost in a one-room dungeon. 🗝️',
  '{u}, your hype is louder than your results. 📣',
  '{u} is the final boss of bad decisions. 👾',
  '{u}, you\'re so predictable even the bots meta you. 🤖',
  '{u} brings the team morale down just by typing. ⌨️',
  '{u}, your skill tree is just a stump. 🪵',
  '{u} got carried so far they have frequent flyer miles. ✈️',
  '{u}, you move like you\'re paying per step. 💰',
  '{u} makes rookie mistakes with veteran confidence. 🎖️',
  '{u}, even your screen saver plays better. 🖥️',
  '{u} has a black belt in feeding. 🥋',
  '{u}, you\'re the side quest nobody finishes. 🗺️',
  '{u} thinks "farm" means planting kamote. 🍠',
  '{u}, your reflexes are still on dial-up. 📞',
  '{u} dies first so they can spectate the win. 👻',
  '{u}, your battle IQ is on a low battery. 🪫',
  '{u} could get lost following a straight arrow. ➡️',
  '{u}, you\'re the reason we practice. As a warning. 📛',
  '{u} plays like the monitor is off. 🖥️',
  '{u}, you\'re not unlucky — you\'re just bad. 🎲',
  '{u} would lose rock-paper-scissors to a rock. 🪨',
  '{u}, the enemy team has a group chat about you. 💬',
  '{u} thinks "combo" is a fast food meal. 🍔',
  '{u}, you hit harder in chat than in the game. 💬',
  '{u} brings the lag wherever they go. 🌩️',
  '{u}, even the loading bar is faster than you. 📶',
  '{u} shows up just to donate points to the enemy. 🎁',
  '{u}, you\'re the 404 of this squad: skill not found. 🔍',
  '{u} gets hyped for the match and forgets to ready up. ✅',
  '{u}, your teammates start a prayer circle when you queue. 🕯️',
  '{u} rushes in like rent is due. 🏃💸',
  '{u}, you\'re a myth — nobody has seen you win. 🦄',
  '{u} still thinks the enemy is on mute. They\'re laughing. 😂',
  '{u}, even your pet could climb ranks faster. 🐕',
  '{u}, your gameplay is a group chat left on read. 📵',
];

export const praises = [
  '{u}, you\'re the MVP this server doesn\'t deserve. 🏆',
  '{u} carries harder than a delivery rider on payday. 🛵📦',
  '{u}, your game sense is on another level. 🧠',
  '{u} makes every team better just by joining. 🤝',
  '{u}, your aim is so clean it should be illegal. 🎯',
  '{u} shows up on time for every Mine Wars. Legend behavior. ⏰⛏️',
  '{u}, the enemy team checks if you\'re online before queueing. 👀',
  '{u} is the teammate everyone wishes they had. 🌟',
  '{u}, you\'re the reason we win Ancient Battlefield. ⚔️',
  '{u} has main character energy AND main character results. 🎬',
  '{u}, your positioning is chef\'s kiss. 👨‍🍳💋',
  '{u} brings good vibes wherever they go. ☀️',
  '{u}, you\'re proof that skill and kindness can coexist. 💛',
  '{u} clutches like it\'s nothing. Absolute cinema. 🎥',
  '{u}, your strategy? Flawless. Your execution? Even better. 📈',
  '{u} is the human version of a buff. ⬆️',
  '{u}, the respawn button misses you — you never need it. 🔁',
  '{u} doesn\'t chase the meta. The meta chases them. 📖',
  '{u}, your calm under pressure is inspiring. 🧘',
  '{u} is a certified carry. Stamp of approval. ✅',
  '{u}, you make hard things look easy. ✨',
  '{u} lights up the chat every time they speak. 💬',
  '{u}, your teammates sleep peacefully knowing you\'re in the squad. 😌',
  '{u} is the reason this server feels like home. 🏠',
  '{u}, you\'re not just good — you\'re consistently good. 📊',
  '{u} has reflexes faster than a Wi-Fi reconnect. ⚡',
  '{u}, the tutorial should be based on your gameplay. 🎓',
  '{u} is a whole highlight reel. 🎞️',
  '{u}, you\'re the rare teammate who says "nice try" and means it. 🫶',
  '{u} plays like they wrote the patch notes. 📝',
  '{u}, your leadership turns chaos into victory. 🧭',
  '{u} is the definition of reliable. 🪨',
  '{u}, even your losses look like practice for greatness. 🌱',
  '{u} deserves a statue in the lobby. 🗿',
  '{u}, the scoreboard gets excited when you join. 🔢',
  '{u} is the sunshine in our 7 AM greetings. 🌅',
  '{u}, you\'re a limited edition — limited to the best. 🏷️',
  '{u} doesn\'t get lucky. They get it done. 💪',
  '{u}, everyone wants you on their team, and it shows. 🙌',
  '{u} is a legend. The good kind. 📜',
  '{u}, your gameplay deserves its own highlight channel. 📺',
  '{u} shows up for Mine Wars like it\'s a sacred duty. ⛏️🫡',
  '{u}, the squad feels stronger the moment you log in. 💪',
  '{u} makes clutch plays look like a walk in the park. 🌳',
  '{u}, your comeback arcs are movie-worthy. 🎬',
  '{u} is the reason the team chat stays positive. 💬',
  '{u}, your map awareness is basically a satellite. 🛰️',
  '{u} turns losing matches into wins. Magic. 🪄',
  '{u}, you\'re the calm in every storm. ⛈️🧘',
  '{u} plays like they read the enemy\'s mind. 🧠',
  '{u}, even the enemy team respects you. 🤝',
  '{u} is the first to help and the last to complain. 🙌',
  '{u}, your timing is chef-level precise. ⏱️👨‍🍳',
  '{u} makes the whole server feel welcome. 🏡',
  '{u}, your aim should be studied by scientists. 🔬',
  '{u} is proof that practice pays off. 📈',
  '{u}, your teammates brag about playing with you. 🗣️',
  '{u} lights up voice chat with good energy. 🔊✨',
  '{u}, you\'re basically a walking buff. 🆙',
  '{u} doesn\'t just play the game — they play it beautifully. 🎨',
  '{u}, your strategies deserve a book deal. 📚',
  '{u} makes hard mode look like easy mode. 🎮',
  '{u}, you\'re the MVP even when the scoreboard disagrees. 🏅',
  '{u} is the teammate who remembers everyone\'s birthday. 🎂',
  '{u}, your patience is legendary. 🕊️',
  '{u} always has the team\'s back. 🛡️',
  '{u}, you bring the snacks AND the wins. 🍿🏆',
  '{u} could carry a team of sleeping cats to victory. 🐈',
  '{u}, your consistency is inspiring. 📊',
  '{u} is a certified vibe provider. 🎶',
  '{u}, your leadership turns strangers into a squad. 🧭',
  '{u} makes every match a masterclass. 🎓',
  '{u}, the Tanod salutes you. 🫡',
  '{u} is the heart of this barangay. ❤️',
  '{u}, your reflexes are faster than Globe promos disappearing. ⚡',
  '{u} makes the 7 AM greeting worth waking up for. 🌅',
  '{u}, your kindness is as strong as your gameplay. 💛',
  '{u} never gives up, even at 0 HP. ❤️‍🩹',
  '{u}, you make Ancient Battlefield feel easy. ⚔️',
  '{u} is the reason we win more than we lose. 🏆',
  '{u}, you\'re the energy drink of this server. 🥤',
  '{u} gives the best advice without being asked. 💡',
  '{u}, your positioning is textbook perfect. 📖',
  '{u} is the kind of player who makes everyone better. 🌱',
  '{u}, you deserve a statue in the plaza. 🗿',
  '{u} brings sunshine even on rainy days. 🌦️',
  '{u}, your clutch factor is off the charts. 📈',
  '{u} is the definition of team player. 🤝',
  '{u}, the scoreboard is lucky to have your name. 🔢',
  '{u} can turn any loss into a lesson and any lesson into a win. 🔁',
  '{u}, you\'re a legend in the making. 📜',
  '{u} is so good, the enemy team asks for tips. 📝',
  '{u}, you make the impossible look routine. ✨',
  '{u} handles pressure like a pro. 💎',
  '{u}, your gameplay is pure poetry. 🖋️',
  '{u} is always on time. Respect. ⏰',
  '{u}, your support plays save lives. Virtual ones, but still. 🩹',
  '{u} is the friend everyone wants in their corner. 🥊',
  '{u}, you\'re the reason this squad has a winning record. 🏅',
  '{u} makes every moment funnier. 😂',
  '{u}, your game sense is sharper than a fresh knife. 🔪',
  '{u} deserves a crown and a cape. 👑🦸',
  '{u}, you radiate main character energy. 🌟',
  '{u} is a hero without the need for a respawn. 🦸',
  '{u}, your decision-making is chef\'s kiss. 💋',
  '{u} makes the team feel unstoppable. 🚀',
  '{u}, you\'re a whole mood booster. 🎈',
  '{u} could win a match with their eyes closed. 😎',
  '{u}, your wins are well-deserved. 🏆',
  '{u} is loyal, reliable, and awesome. 🐕',
  '{u}, your hustle is unmatched. 💼',
  '{u} has the skills to pay the bills. 💸',
  '{u}, you bring out the best in everyone. 🌻',
  '{u} is the calmest person in the most chaotic fights. 🌪️🧘',
  '{u}, your plays belong in a museum. 🏛️',
  '{u} makes grinding feel fun. ⚙️',
  '{u}, you\'re the secret weapon we don\'t talk about. 🤫',
  '{u} is the unsung hero of every win. 🎵',
  '{u}, your energy is contagious in the best way. ⚡',
  '{u} is basically a cheat code, but legal. 🎮',
  '{u}, we\'d follow you into any battle. ⚔️',
  '{u} knows when to push and when to wait. Genius. 🧠',
  '{u}, you\'ve got the heart of a champion. 🏆❤️',
  '{u} makes every squad feel like family. 🏠',
  '{u}, your jokes are as good as your gameplay. 😄',
  '{u} always shares the loot. Legend. 🎁',
  '{u}, you make winning look effortless. 🌟',
  '{u} is proof that nice people can finish first. 🥇',
  '{u}, you\'re the brightest star in this server. ⭐',
  '{u} could lead an army with just a thumbs up. 👍',
  '{u}, your gaming skills are elite. 🏅',
  '{u} makes the late-night matches worth it. 🌙',
  '{u}, you\'re a total legend, no cap. 🧢',
  '{u} always keeps the vibes immaculate. ✨',
  '{u}, you\'re the first pick in every team. 🥇',
  '{u} deserves a lifetime supply of kape. ☕',
  '{u}, your support never goes unnoticed. 👀💛',
  '{u} is the reason we stay up way too late. 🌃',
  '{u}, you turn every match into a highlight. 🎞️',
  '{u} is a force of nature. 🌋',
  '{u}, your teammates feel safe with you around. 🛡️',
  '{u} plays with style and heart. 💃❤️',
  '{u}, you\'re unstoppable when you lock in. 🔒',
  '{u} gives 100% every single time. 💯',
  '{u}, you inspire the whole squad to level up. 🆙',
  '{u} is the calm voice in voice chat. 🎧',
  '{u}, the server wouldn\'t be the same without you. 🏘️',
  '{u} is a whole package: skill, heart, and humor. 🎁',
  '{u}, you make every loss feel like a practice round. 🌱',
  '{u} is a true champion of the barangay. 🏅',
  '{u}, your gameplay is so clean it sparkles. 🧼✨',
  '{u} is the reason the enemy team rage quits. 😤',
  '{u}, you could teach a masterclass in teamwork. 🎓',
  '{u} makes every team comp work. 🧩',
  '{u}, you\'re a blessing to this squad. 🙏',
  '{u} always knows what to say to lift spirits. 💬💛',
  '{u}, your hard work shows in every match. 💪',
  '{u} makes the grind worth it. 🏋️',
  '{u}, you\'re a rare gem. 💎',
  '{u} is the reason the squad keeps smiling. 😊',
  '{u}, you shine brighter than a Christmas parol. 🌟🎄',
  '{u} brings the win and the good vibes. 🏆🎶',
  '{u}, your aim is laser-guided. 🎯',
  '{u} is the best teammate this side of the internet. 🌐',
  '{u}, you make the tough calls and they work. ✅',
  '{u} deserves all the credits in the world. 🪙',
  '{u}, you\'re basically the team\'s lucky charm. 🍀',
  '{u} can read the game like a favorite book. 📖',
  '{u}, your gameplay makes the Tanod proud. 🫡',
  '{u} keeps showing up and leveling up. 📈',
  '{u}, you are the hype. 📣',
  '{u} makes every day in this server better. ☀️',
  '{u}, you\'re a true barangay hero. 🦸',
  '{u} brings leadership, loyalty, and laughs. 🧭😂',
  '{u}, your skills are next level. 🆙',
  '{u} is the reason Mine Wars feels like a party. 🎉⛏️',
  '{u}, your presence is a power-up. 🍄',
  '{u} makes strategy look simple. ♟️',
  '{u}, you\'re the heart and soul of the squad. 💖',
  '{u} always plays fair and plays well. ⚖️',
  '{u}, you\'ve got that winner\'s mindset. 🧠🏆',
  '{u} could make a potato team win. 🥔🏆',
  '{u}, your teammates owe you a merienda. 🍞',
  '{u} makes it look easy every time. 😌',
  '{u}, you are simply the best. 🥇',
  '{u} is a gift to this community. 🎁',
  '{u}, your vibes could power the whole barangay. ⚡🏘️',
  '{u} is the steady rock of the team. 🪨',
  '{u}, you make the squad feel like champions. 🏆',
  '{u} is the friend who never leaves anyone behind. 🤝',
  '{u}, you\'re a total inspiration. ✨',
  '{u} keeps the squad laughing and winning. 😂🏆',
  '{u}, you\'re a walking highlight reel. 🎥',
  '{u} is the reason we love game night. 🌙🎮',
  '{u}, you\'re the gold standard. 🥇',
  '{u} deserves a standing ovation. 👏',
  '{u}, your good energy is unmatched. 🔋',
  '{u} always shows up when it matters most. ⏰',
  '{u}, you make every squad better just by being in it. 🌈',
  '{u}, the Tanod would trust you with the whole barangay. 🫡🏘️',
];

// When someone judges the bot.
export const botComebacks = [
  'Nice try. I run 24/7 on a free server and I still have better uptime than you. 😎',
  'You tried to diss the bot. The bot is not impressed. 🤖',
];

export const botPraises = [
  'Aww, thank you! I\'ll keep being on time, 24/7. 🥹🤖',
  'You praised the bot. The bot is blushing in binary. 01100010 🤖💖',
];
